`timescale 1ns/1ps

module fifo_system #(
    parameter DATA_WIDTH = 8,// width of data
    parameter PARITY_BITS = 4,// number of Hamming parity bits
    parameter DEPTH = 16,// no. of FIFO entries
    parameter ADDR_WIDTH = $clog2(DEPTH),// bits required for address
    parameter SYNC_STAGES = 2,// no. of synchronizer stages

    parameter AFULL_LEVEL = DEPTH-2,
    parameter AEMPTY_LEVEL = 2,
    parameter PFULL_LEVEL = DEPTH-4,
    parameter PEMPTY_LEVEL = 4
)(
    // Write side
    input wire wr_clk,
    input wire wr_rst,
    input wire wr_en,
    input wire [DATA_WIDTH-1:0] din,

    // Read side
    input wire rd_clk,
    input wire rd_rst,
    input wire rd_en,

    output wire [DATA_WIDTH-1:0] dout,

    // FIFO status
    output wire full,
    output wire empty,
    output wire almost_full,
    output wire almost_empty,
    output wire prog_full,
    output wire prog_empty,

    // ECC status
    output wire ecc_single_error,
    output wire ecc_double_error
);

    wire [DATA_WIDTH-1:0] fifo_dout; // Data coming from async FIFO before it passes through FWFT wrapper.
    
    wire fifo_rd_en;// read request generated by the FWFT wrapper.

    wire fifo_empty;


    // Async FIFO

    // The async FIFO handles the storage, CDC, ECC and FIFO status flags.
    async_fifo #(
        .DATA_WIDTH(DATA_WIDTH),
        .PARITY_BITS(PARITY_BITS),
        .DEPTH(DEPTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .SYNC_STAGES(SYNC_STAGES),

        .AFULL_LEVEL(AFULL_LEVEL),
        .AEMPTY_LEVEL(AEMPTY_LEVEL),
        .PFULL_LEVEL(PFULL_LEVEL),
        .PEMPTY_LEVEL(PEMPTY_LEVEL)
    ) fifo_inst (

        .wr_clk(wr_clk),
        .wr_rst (wr_rst),
        .wr_en(wr_en),
        .din(din),

        .rd_clk(rd_clk),
        .rd_rst(rd_rst),
        .rd_en(fifo_rd_en),
        .dout(fifo_dout),

        .full(full),
        .empty(fifo_empty),
        .almost_full(almost_full),
        .almost_empty(almost_empty),
        .prog_full(prog_full),
        .prog_empty(prog_empty),

        .ecc_single_error(ecc_single_error),
        .ecc_double_error(ecc_double_error)
    );


    // FWFT Wrapper

// The wrapper manages the FIFO read requests and keeps the next available word on dout 
    fwft_wrapper #(
        .DATA_WIDTH(DATA_WIDTH)
    ) fwft_inst (

        .clk(rd_clk),
        .rst(rd_rst),

        .fifo_dout(fifo_dout),
        .fifo_empty(fifo_empty),
        .fifo_rd_en(fifo_rd_en),

        .dout(dout),
        .empty(empty),
        .rd_en(rd_en)
    );

endmodule