`timescale 1ns/1ps

module fifo_system #(
    parameter DATA_WIDTH  = 8,
    parameter PARITY_BITS = 4,
    parameter DEPTH       = 16,
    parameter ADDR_WIDTH  = $clog2(DEPTH),
    parameter SYNC_STAGES = 2,

    parameter AFULL_LEVEL  = DEPTH-2,
    parameter AEMPTY_LEVEL = 2,
    parameter PFULL_LEVEL  = DEPTH-4,
    parameter PEMPTY_LEVEL = 4
)(
    // Write side
    input wire                   wr_clk,
    input wire                   wr_rst,
    input wire                   wr_en,
    input wire [DATA_WIDTH-1:0]  din,

    // Read side
    input wire                   rd_clk,
    input wire                   rd_rst,
    input wire                   rd_en,

    output wire [DATA_WIDTH-1:0] dout,

    // FIFO status
    output wire full,
    output wire empty,
    output wire almost_full,
    output wire almost_empty,
    output wire prog_full,
    output wire prog_empty,

    // ECC status
    output wire ecc_single_error,
    output wire ecc_double_error
);

    // Data coming directly from the async FIFO.
    wire [DATA_WIDTH-1:0] fifo_dout;

    // Read request generated by the FWFT wrapper.
    wire fifo_rd_en;

    // FIFO empty status used by the FWFT wrapper.
    wire fifo_empty;


    // --------------------------------------------------
    // Async FIFO
    // --------------------------------------------------

    async_fifo #(
        .DATA_WIDTH  (DATA_WIDTH),
        .PARITY_BITS (PARITY_BITS),
        .DEPTH       (DEPTH),
        .ADDR_WIDTH  (ADDR_WIDTH),
        .SYNC_STAGES (SYNC_STAGES),

        .AFULL_LEVEL  (AFULL_LEVEL),
        .AEMPTY_LEVEL (AEMPTY_LEVEL),
        .PFULL_LEVEL  (PFULL_LEVEL),
        .PEMPTY_LEVEL (PEMPTY_LEVEL)
    ) fifo_inst (

        .wr_clk (wr_clk),
        .wr_rst (wr_rst),
        .wr_en  (wr_en),
        .din    (din),

        .rd_clk (rd_clk),
        .rd_rst (rd_rst),
        .rd_en  (fifo_rd_en),
        .dout   (fifo_dout),

        .full        (full),
        .empty       (fifo_empty),
        .almost_full (almost_full),
        .almost_empty(almost_empty),
        .prog_full   (prog_full),
        .prog_empty  (prog_empty),

        .ecc_single_error (ecc_single_error),
        .ecc_double_error (ecc_double_error)
    );


    // --------------------------------------------------
    // FWFT Wrapper
    // --------------------------------------------------
    //
    // The wrapper automatically requests the first FIFO
    // word and presents it to the user as soon as it is
    // available.
    // --------------------------------------------------

    fwft_wrapper #(
        .DATA_WIDTH(DATA_WIDTH)
    ) fwft_inst (

        .clk        (rd_clk),
        .rst        (rd_rst),

        .fifo_dout  (fifo_dout),
        .fifo_empty (fifo_empty),
        .fifo_rd_en (fifo_rd_en),

        .dout       (dout),
        .empty      (empty),

        .rd_en      (rd_en)
    );

endmodule